name: Check Version on Release

on:
  push:
  # release:
  #   types: [published]

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Version Check
        run: |
          release_version=$(git tag --sort=v:refname | tail -n 1)
          python_version=$(grep -oP '(?<=version = ")[^"]*' pyproject.toml)
          if test "$version_to_release" != "$python_version"; then
            echo "Release version ($release_version) differs to the version in pyproject.toml ($python_version)"
            exit 1
          fi
