name: Check Version on Release

on:
  push:
  # release:
  #   types: [published]

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Version Check
        run: |
          version_to_release=$(git tag --sort=v:refname | tail -n 1)
          python_version=$(grep -oP '(?<=version = ")[^"]*' pyproject.toml)
          echo "release version is $version_to_release"
          echo "python version is $python_version"
          if test "$version_to_release" != "$python_version"; then
            echo "Versions differ"
            exit 1
          fi
